- hosts: localhost
  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
    personal: "{{ lookup('env', 'HOME') }}/personal"
  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
    tags:
      - install
      - core
  tasks:
    - name: SSH Install
      include_tasks: tasks/ssh.yml
      tags: ssh

#    - include_tasks: tasks/dotfiles.yml
    - include_tasks: tasks/core-setup.yml
    
    - name: Node
      include_tasks: tasks/node-setup.yml
      tags: node

    - name: Npm Packages
      include_tasks: tasks/npm-packages.yml
      tags: npm-packages

    - name: Include nvim
      include_tasks: tasks/nvim-setup.yml
      tags: neovim
        
    - name: Lua lsp
      include_tasks: tasks/lsp.yml
      tags: lsp

    - name: install-slack
      include_tasks: tasks/slack-setup.yml
      tags: slack

    - name: Install Aws
      include_tasks: tasks/aws-setup.yml
      tags: aws

    - name: Intstall Brave
      include_tasks: tasks/brave.yml
      tags: brave

    - name: Include Debugge
      include_tasks: tasks/debugger.yml
      tags: debugger
  
    - name: Productivity Tools
      include_tasks: tasks/productivity-tools.yml
      tags: productivity

        #    - name: Docker
        #      include_tasks: tasks/docker.yml
        #      tags: docker

