- name: remove aws if has
  ansible.builtin.file:
    path: '{{ personal }}/tmp/aws'
    state: absent
  tags:
  - aws

- name: create aws folder
  ansible.builtin.file:
    path: '{{ personal }}/tmp/aws'
    state: directory
    mode: '0755'
  tags:
  - aws

- name: download aws command line
  ansible.builtin.get_url:
    url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
    dest: '{{ personal }}/tmp/aws/awscliv2.zip'
    mode: '0440'
  tags:
  - aws

- name: Install aws command line
  shell: cd {{ personal }}/tmp/aws | unzip awscliv2.zip | sudo aws/./install
  tags:
  - aws
