- name: Add Docker requared packages
  become: true
  apt:
    name: ["ca-certificates", "gnupg", "lsb-release"]
    state: present
  tags:
    - docker
- name: Remove old docker
  become: true
  apt:
    name: ["docker", "docker-engine", "docker.io", "containerd", "runc"]
    state: absent
  tags:
    - docker
- name: Add docker key folder
  file:
    path: /etc/apt/keyrings
    state: directory
    recurse: yes
  tags:
    - docker
- name: Add Docker official GPG key
  shell: cd /etc/apt/keyrings/ | curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  tags:
  - docker
- name: Set up the repository
  shell: echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  tags:
  - docker
- name: Add Docker
  become: true
  apt:
    name: ["docker.io", "docker-ce-cli", "containerd.io", "docker-compose-plugin"]
    state: present
  tags:
    - docker
