- name: Remove slack
  community.general.snap:
    name: slack
    state: absent
  tags:
    - install
    - slack

- name: Install slack 
  community.general.snap:
    name: slack
  tags:
    - install
    - slack
